backstage = false
checkssh = true
cloudinarycloudname = 'dlwdq84ig'
configdirectory = 'C:\projects\frontastic-cli\.frontastic'
customername = 'demo'
customtasticsroot = ''
filesync = false
https = true
ismultitenant = false
lastversioncheck = '2023-01-30 14:17:32.5611362 +0100 CET'
latestversion = '1.25.0'
projectname = 'english'
projectroot = 'C:\projects\frontastic-cli'
remoteserverhostname = 'english-demo.frontastic.io'
studioapiusertoken = ''
syncfrontend = false
traefikdashboardconfigpath = 'C:\projects\frontastic-cli\.frontastic\traefik_config\dashboard.toml'
traefikssrconfigpath = 'C:\projects\frontastic-cli\.frontastic\traefik_config\ssr.toml'
traefikwebpackconfigpath = 'C:\projects\frontastic-cli\.frontastic\traefik_config\webpack.toml'
